language: php

sudo: false

cache:
    apt: true
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
          env: CS_FIXER=run
        - php: hhvm

before_install:
    - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

before_script:
    - composer --prefer-dist install --no-interaction -o --no-progress

script:
    - php vendor/bin/simple-phpunit -v
    - if [ "$CS_FIXER" = "run" ]; then php vendor/bin/php-cs-fixer fix --verbose --dry-run ; fi;
