language: php

sudo: false

cache:
    apt: true
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
          env: CS_FIXER=run
        - php: nightly
        - php: hhvm-3.12
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm
          sudo: required
          dist: trusty
          group: edge
    allow_failures:
        - php: nightly
        - php: hhvm-3.12
        - php: hhvm
    fast_finish: true

install:
    # php-cs-fixer conflict with HHVM
    - if [[ $TRAVIS_PHP_VERSION = 'hhvm' ]]; then composer remove friendsofphp/php-cs-fixer --dev; fi

before_script:
    - composer --prefer-dist install --no-interaction -o --no-progress

script:
    - php vendor/bin/simple-phpunit -v
    - if [ "$CS_FIXER" = "run" ]; then php vendor/bin/php-cs-fixer fix --verbose --dry-run ; fi;
